# config/packages/workflow.yaml
framework:
    workflows:
        blog_publishing:
            type: 'workflow' # or 'state_machine'
            audit_trail:
                enabled: true
            marking_store:
                type: 'method'
                property: 'currentPlace'
            supports:
                - App\Entity\Article
            initial_marking: draft
            places:
                - !php/const App\Entity\Article::STATE_DRAFT
                - !php/const App\Entity\Article::STATE_REVIEWED
                - !php/const App\Entity\Article::STATE_REJECTED
                - !php/const App\Entity\Article::STATE_PUBLISHED
            transitions:
                mark_as_reviewed:
                    from: draft
                    to:   reviewed
                publish:
                    from: reviewed
                    to:   published
                reject:
                    from: reviewed
                    to:   rejected